[package]
name = "antlr-rust-runtime-testsuite"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Integration-test harness for the ANTLR upstream runtime conformance suite"
repository.workspace = true
homepage.workspace = true
license.workspace = true
publish = false

[[bin]]
name = "antlr4-runtime-testsuite"
path = "src/main.rs"

[dependencies]
antlr-rust-runtime.workspace = true
antlr-rust-codegen.workspace = true
icu_properties.workspace = true

[lints]
workspace = true
