[package]
categories             = ["parser-implementations", "parsing"]
description            = "TOML parser used internally by antlr-rust-codegen"
edition.workspace      = true
homepage.workspace     = true
include                = ["/Cargo.toml", "/LICENSE", "/NOTICE", "/README.md", "/src/**"]
keywords               = ["antlr", "antlr4", "parser", "toml"]
license                = "Apache-2.0"
name                   = "antlr-rust-toml-parser"
publish                = true
readme                 = "README.md"
repository.workspace   = true
rust-version.workspace = true
version.workspace      = true

[dependencies]
antlr-rust-runtime.workspace = true
toml_datetime.workspace = true

[dev-dependencies]
insta.workspace = true

[lints]
workspace = true
