// @generated by antlr-rust-codegen v0.32.0 - do not edit
// project: https://github.com/ophi-dev/antlr-rust-runtime
antlr4_runtime::__antlr4_rust_require_codegen_api!(9, "0.32.0");
#[allow(warnings, missing_docs, clippy::all, clippy::pedantic, clippy::nursery)]
#[rustfmt::skip]
mod __antlr4_rust_generated {

use antlr4_runtime::token::TokenSource;
use antlr4_runtime::token_stream::CommonTokenStream;
use antlr4_runtime::atn::parser_atn::ParserAtn;
use antlr4_runtime::{BaseParser, GrammarMetadata, Parser, Recognizer};
use std::sync::OnceLock;
#[allow(unused_imports)]
use std::io::Write as _;
#[allow(unused_imports)]
use antlr4_runtime::{java_style_list, PredictionMode, BailErrorStrategy, TerminalNodeView as RuntimeTerminalNode, ErrorNodeView as RuntimeErrorNode, RuleNodeView, AsRuleNode, FromRuleNode, MissingChildError, Token as _};
pub use antlr4_runtime::generated::{ErrorNode, StoredTreeContext, TerminalNode, __GeneratedInput, __GeneratedTokenView};
#[allow(unused_imports)]
use antlr4_runtime::generated::{__ActiveParserContext, __FromActiveRuleContext, __GeneratedRuleContext, __RecoveryContextState, __active_context_view, __active_context_view_with_attrs, __context_children, __labeled_token_children, __labeled_token_children_matching, __rule_children, __terminal_children, __token_children, __token_children_matching, __write_invocation_states};


pub const EOF: i32 = antlr4_runtime::TOKEN_EOF;
pub const ID: i32 = 1;
pub const WS: i32 = 2;

pub const RULE_ROOT: usize = 0;

pub static METADATA: GrammarMetadata = GrammarMetadata::new(
    "CodegenApiParser",
    &["root"],
    &[None, None, None],
    &[None, Some("ID"), Some("WS")],
    &[None, None, None],
    &[],
    &[],
    &[],
);

pub fn metadata() -> &'static GrammarMetadata {
    &METADATA
}

pub fn rule_names() -> &'static [&'static str] {
    METADATA.rule_names()
}

fn parser_semantics() -> &'static antlr4_runtime::ParserSemantics {
    static SEMANTICS_CELL: OnceLock<antlr4_runtime::ParserSemantics> = OnceLock::new();
    SEMANTICS_CELL.get_or_init(|| {
        let mut ir = antlr4_runtime::semir::SemIr::new();
        let mut predicates = Vec::new();

        let actions = Vec::new();
        antlr4_runtime::ParserSemantics { ir, predicates, actions }
    })
}



/// Marker carried by generated contexts whose required-child
/// invariants were checked after a syntax-clean parse.
///
/// This marker stays module-local (unlike the runtime-owned support items)
/// so rustc can prove it never implements the runtime's
/// `__RecoveryContextState`, keeping the recovery-oriented and validated
/// accessor impls coherent.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct ValidatedTreeContext {
    __private: (),
}

/// A completed, syntax-clean parse tree whose generated child cardinalities
/// have been structurally validated.
#[derive(Debug)]
pub struct CodegenApiValidatedTree {
    parsed: antlr4_runtime::ParsedFile,
}

impl CodegenApiValidatedTree {
    fn __new(parsed: antlr4_runtime::ParsedFile) -> Self {
        Self { parsed }
    }

    /// Returns the validated entry-rule root.
    pub fn tree(&self) -> ValidatedRuleNode<'_> {
        let Some(rule) = self.parsed.tree().as_rule() else {
            unreachable!("validated parse root was checked as a rule node")
        };
        ValidatedRuleNode { __node: rule }
    }

    /// Borrows the underlying recovery-oriented parsed file.
    pub const fn parsed_file(&self) -> &antlr4_runtime::ParsedFile {
        &self.parsed
    }

    /// Drops the validation type boundary and returns the underlying parsed file.
    pub fn into_parsed_file(self) -> antlr4_runtime::ParsedFile {
        self.parsed
    }
}

/// A rule node borrowed from a [`CodegenApiValidatedTree`].
#[derive(Clone, Copy, Debug)]
pub struct ValidatedRuleNode<'a> {
    __node: RuleNodeView<'a>,
}

impl<'a> ValidatedRuleNode<'a> {
    pub const fn rule_node(self) -> RuleNodeView<'a> {
        self.__node
    }

    pub const fn node(self) -> antlr4_runtime::Node<'a> {
        self.__node.node()
    }

    pub fn rule_index(self) -> usize {
        self.__node.rule_index()
    }

    pub fn text(self) -> String {
        self.__node.text()
    }

    pub fn downcast_ref<T: FromValidatedRuleNode<'a>>(self) -> Option<T> {
        T::from_validated_rule_node(self)
    }
}

/// Constructs a generated validated context from a validated rule node.
pub trait FromValidatedRuleNode<'a>: Sized {
    fn from_validated_rule_node(node: ValidatedRuleNode<'a>) -> Option<Self>;
}

/// Failure to recognize or validate a strict generated parse.
#[derive(Clone, Debug, Eq, PartialEq)]
pub enum CodegenApiValidationError {
    Recognition(antlr4_runtime::AntlrError),
    SyntaxErrors {
        lexer: usize,
        parser: usize,
    },
    MissingChild(MissingChildError),
    InvalidChildCount {
        context: &'static str,
        child: &'static str,
        minimum: usize,
        actual: usize,
    },
    RecoveredErrorNode {
        line: usize,
        column: usize,
        text: String,
    },
    InvalidRoot,
    UnknownRule {
        rule_index: usize,
    },
}

impl std::fmt::Display for CodegenApiValidationError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Recognition(error) => write!(f, "parse failed: {error}"),
            Self::SyntaxErrors { lexer, parser } => write!(
                f,
                "parse produced {lexer} lexer and {parser} parser syntax errors"
            ),
            Self::MissingChild(error) => error.fmt(f),
            Self::InvalidChildCount {
                context,
                child,
                minimum,
                actual,
            } => write!(
                f,
                "required child {child} occurs {actual} times in {context}; expected at least {minimum}"
            ),
            Self::RecoveredErrorNode {
                line,
                column,
                text,
            } => write!(
                f,
                "recovered error node at {line}:{column}: {text}"
            ),
            Self::InvalidRoot => f.write_str("validated parse root is not a rule node"),
            Self::UnknownRule { rule_index } => write!(
                f,
                "parse tree contains unknown rule index {rule_index}"
            ),
        }
    }
}

impl std::error::Error for CodegenApiValidationError {
    fn source(&self) -> Option<&(dyn std::error::Error + 'static)> {
        match self {
            Self::Recognition(error) => Some(error),
            Self::MissingChild(error) => Some(error),
            _ => None,
        }
    }
}

impl From<antlr4_runtime::AntlrError> for CodegenApiValidationError {
    fn from(error: antlr4_runtime::AntlrError) -> Self {
        Self::Recognition(error)
    }
}

impl From<MissingChildError> for CodegenApiValidationError {
    fn from(error: MissingChildError) -> Self {
        Self::MissingChild(error)
    }
}

#[allow(dead_code)]
fn __context_kind(context: RuleNodeView<'_>) -> usize {
    context.rule_index()
}

#[allow(dead_code)]
fn __active_context_kind(
    context: &antlr4_runtime::ParserRuleContext,
    _storage: &antlr4_runtime::ParseTreeStorage,
    _tokens: &antlr4_runtime::TokenStore,
) -> usize {
    context.rule_index()
}

antlr4_runtime::__antlr4_rust_context! {
    pub struct RootContext {
        rule_index: 0,
        context_kind: any,
        attributes: {
        },
        methods: {
            rule_node: rule_node,
            child_count: child_count,
            direct_terminals: direct_terminals,
            start: start,
            text: text,
        }
    }
}

antlr4_runtime::__antlr4_rust_context_accessors! {
    RootContext {
        token eof_token: required(-1, "EOF"),
        token id_token: required(1, "ID"),
    }
}

/// Checks generated required-child invariants without changing the
/// recovery-oriented tree's type.
///
/// Strict parsing calls this after proving that lexer and parser syntax-error
/// counts are both zero. It is public so structural runtime/codegen invariant
/// failures can be diagnosed independently.
pub fn validate_tree_structure(
    parsed: &antlr4_runtime::ParsedFile,
) -> Result<(), CodegenApiValidationError> {
    let tree = parsed.tree();
    if tree.as_rule().is_none() {
        return Err(CodegenApiValidationError::InvalidRoot);
    }
    for node in tree.descendants() {
        match node.kind() {
            antlr4_runtime::NodeKind::Terminal => {}
            antlr4_runtime::NodeKind::Error => {
                let symbol = node
                    .as_error()
                    .expect("error node kind checked")
                    .symbol();
                return Err(CodegenApiValidationError::RecoveredErrorNode {
                    line: symbol.line(),
                    column: symbol.column(),
                    text: symbol.text_or_empty().to_owned(),
                });
            }
            antlr4_runtime::NodeKind::Rule => {
                let context = node.as_rule().expect("rule node kind checked");
                match __context_kind(context) {
                0 => {
                    let context = RootContext::__from_listener_node(context, None);
        let _ = context.eof_token().map_err(CodegenApiValidationError::MissingChild)?;
        let _ = context.id_token().map_err(CodegenApiValidationError::MissingChild)?;
                },
                    _ => {
                        return Err(CodegenApiValidationError::UnknownRule {
                            rule_index: context.rule_index(),
                        });
                    }
                }
            }
        }
    }
    Ok(())
}

#[allow(dead_code, unused_variables)]
pub trait CodegenApiListener<E = std::convert::Infallible> {
    fn walk(&mut self, tree: antlr4_runtime::Node<'_>) -> Result<(), E>
    where
        Self: Sized,
    {
        CodegenApiTreeWalker::walk(self, tree)
    }

    fn enter_every_rule(&mut self, _ctx: RuleNodeView<'_>) -> Result<(), E> { Ok(()) }
    fn exit_every_rule(&mut self, _ctx: RuleNodeView<'_>) -> Result<(), E> { Ok(()) }

    fn enter_root(&mut self, _ctx: &RootContext) -> Result<(), E> { Ok(()) }
    fn exit_root(&mut self, _ctx: &RootContext) -> Result<(), E> { Ok(()) }
    fn visit_terminal(&mut self, _node: &TerminalNode) -> Result<(), E> { Ok(()) }
    fn visit_error_node(&mut self, _node: &ErrorNode) -> Result<(), E> { Ok(()) }
    fn output(&mut self) -> std::io::Stdout { std::io::stdout() }
}

#[allow(dead_code)]
pub struct CodegenApiTreeWalker;

#[allow(dead_code)]
impl CodegenApiTreeWalker {
    pub fn walk<E, T: CodegenApiListener<E>>(
        listener: &mut T,
        tree: antlr4_runtime::Node<'_>,
    ) -> Result<(), E> {
        Self::__walk(listener, tree, None)
    }

    pub fn walk_with_invocation_states<E, T: CodegenApiListener<E>>(
        listener: &mut T,
        tree: antlr4_runtime::Node<'_>,
        parent_invocation_states: Vec<isize>,
    ) -> Result<(), E> {
        Self::__walk(listener, tree, Some(parent_invocation_states))
    }

    fn __walk<E, T: CodegenApiListener<E>>(
        listener: &mut T,
        tree: antlr4_runtime::Node<'_>,
        mut invocation_states: Option<Vec<isize>>,
    ) -> Result<(), E> {
        enum Event<'tree> {
            Enter(antlr4_runtime::Node<'tree>),
            Exit(RuleNodeView<'tree>),
        }

        let mut stack = vec![Event::Enter(tree)];
        while let Some(event) = stack.pop() {
            match event {
                Event::Enter(node) => match node.kind() {
                    antlr4_runtime::NodeKind::Rule => {
                        let context = node.as_rule().expect("rule node kind checked");
                        if let Some(states) = &mut invocation_states {
                            states.insert(0, context.invoking_state());
                        }
                        listener.enter_every_rule(context)?;
                        match __context_kind(context) {
                        0 => listener.enter_root(&RootContext::__from_listener_node(context, invocation_states.as_deref()))?,
                            _ => {}
                        }
                        stack.push(Event::Exit(context));
                        stack.extend(context.children().rev().map(Event::Enter));
                    }
                    antlr4_runtime::NodeKind::Terminal => {
                        listener.visit_terminal(&TerminalNode::new(
                            node.as_terminal().expect("terminal node kind checked"),
                        ))?;
                    }
                    antlr4_runtime::NodeKind::Error => {
                        listener.visit_error_node(&ErrorNode::new(
                            node.as_error().expect("error node kind checked"),
                        ))?;
                    }
                },
                Event::Exit(context) => {
                    match __context_kind(context) {
                    0 => listener.exit_root(&RootContext::__from_listener_node(context, invocation_states.as_deref()))?,
                        _ => {}
                    }
                    listener.exit_every_rule(context)?;
                    if let Some(states) = &mut invocation_states {
                        states.remove(0);
                    }
                }
            }
        }
        Ok(())
    }
}

pub type ParseTreeWalker = CodegenApiTreeWalker;

#[allow(dead_code, unused_variables)]
pub trait CodegenApiValidatedListener<E = std::convert::Infallible> {
    fn walk(&mut self, tree: ValidatedRuleNode<'_>) -> Result<(), E>
    where
        Self: Sized,
    {
        CodegenApiValidatedTreeWalker::walk(self, tree)
    }

    fn enter_every_rule(&mut self, _ctx: ValidatedRuleNode<'_>) -> Result<(), E> { Ok(()) }
    fn exit_every_rule(&mut self, _ctx: ValidatedRuleNode<'_>) -> Result<(), E> { Ok(()) }

    fn enter_root(&mut self, _ctx: &RootContext<ValidatedTreeContext>) -> Result<(), E> { Ok(()) }
    fn exit_root(&mut self, _ctx: &RootContext<ValidatedTreeContext>) -> Result<(), E> { Ok(()) }
    fn visit_terminal(&mut self, _node: &TerminalNode) -> Result<(), E> { Ok(()) }
    fn output(&mut self) -> std::io::Stdout { std::io::stdout() }
}

#[allow(dead_code)]
pub struct CodegenApiValidatedTreeWalker;

#[allow(dead_code)]
impl CodegenApiValidatedTreeWalker {
    pub fn walk<E, T: CodegenApiValidatedListener<E>>(
        listener: &mut T,
        tree: ValidatedRuleNode<'_>,
    ) -> Result<(), E> {
        Self::__walk(listener, tree.node(), None)
    }

    pub fn walk_with_invocation_states<E, T: CodegenApiValidatedListener<E>>(
        listener: &mut T,
        tree: ValidatedRuleNode<'_>,
        parent_invocation_states: Vec<isize>,
    ) -> Result<(), E> {
        Self::__walk(listener, tree.node(), Some(parent_invocation_states))
    }

    fn __walk<E, T: CodegenApiValidatedListener<E>>(
        listener: &mut T,
        tree: antlr4_runtime::Node<'_>,
        mut invocation_states: Option<Vec<isize>>,
    ) -> Result<(), E> {
        enum Event<'tree> {
            Enter(antlr4_runtime::Node<'tree>),
            Exit(RuleNodeView<'tree>),
        }

        let mut stack = vec![Event::Enter(tree)];
        while let Some(event) = stack.pop() {
            match event {
                Event::Enter(node) => match node.kind() {
                    antlr4_runtime::NodeKind::Rule => {
                        let context = node.as_rule().expect("rule node kind checked");
                        if let Some(states) = &mut invocation_states {
                            states.insert(0, context.invoking_state());
                        }
                        listener.enter_every_rule(ValidatedRuleNode { __node: context })?;
                        match __context_kind(context) {
                        0 => listener.enter_root(&RootContext::<ValidatedTreeContext>::__from_validated_listener_node(context, invocation_states.as_deref()))?,
                            _ => {}
                        }
                        stack.push(Event::Exit(context));
                        stack.extend(context.children().rev().map(Event::Enter));
                    }
                    antlr4_runtime::NodeKind::Terminal => {
                        listener.visit_terminal(&TerminalNode::new(
                            node.as_terminal().expect("terminal node kind checked"),
                        ))?;
                    }
                    antlr4_runtime::NodeKind::Error => {
                        unreachable!("validated parse tree contains an error node")
                    }
                },
                Event::Exit(context) => {
                    match __context_kind(context) {
                    0 => listener.exit_root(&RootContext::<ValidatedTreeContext>::__from_validated_listener_node(context, invocation_states.as_deref()))?,
                        _ => {}
                    }
                    listener.exit_every_rule(ValidatedRuleNode { __node: context })?;
                    if let Some(states) = &mut invocation_states {
                        states.remove(0);
                    }
                }
            }
        }
        Ok(())
    }
}

pub type ValidatedParseTreeWalker = CodegenApiValidatedTreeWalker;



static PARSER_ATN_DATA: &[u32] = &[1346458702, 2, 16909060, 29, 2, 6, 4, 0, 0, 0, 1, 29, 42, 71, 20, 91, 0, 91, 0, 91, 0, 91, 1, 92, 1, 93, 0, 91, 0, 2, 0, 8, 0, 1, 4294967295, 4294967295, 7, 0, 16, 1, 0, 4294967295, 4294967295, 1, 0, 32, 1, 1, 4294967295, 4294967295, 1, 0, 32, 2, 1, 4294967295, 4294967295, 1, 0, 8, 3, 1, 4294967295, 4294967295, 1, 0, 0, 4, 0, 4294967295, 4294967295, 1, 2, 0, 0, 0, 5, 3, 1, 0, 0, 5, 4, 4294967295, 0, 0, 1, 1, 0, 0, 0, 0, 1];
static ATN_CELL: OnceLock<ParserAtn> = OnceLock::new();

/// Validates and caches the packed grammar ATN for all parser instances.
fn atn() -> &'static ParserAtn {
    ATN_CELL.get_or_init(|| {
        ParserAtn::from_static(PARSER_ATN_DATA)
            .unwrap_or_else(|error| panic!("generated parser ATN is incompatible with this runtime: {error}"))
    })
}

/// Borrows the validated packed parser ATN embedded in this module.
pub fn parser_atn() -> &'static ParserAtn {
    atn()
}

/// Result from [`parse_with_parser`] or [`parse_stream_with_parser`].
///
/// Keeps the generated parser available after the entry rule runs so callers
/// can inspect diagnostics or recover the parser-owned token stream.
#[derive(Debug)]
pub struct CodegenApiParserParseOutput<R, L>
where
    L: TokenSource,
{
    pub result: R,
    pub parser: CodegenApiParser<L>,
}

impl<L: TokenSource> CodegenApiParserParseOutput<antlr4_runtime::NodeId, L> {
    /// Validates a completed parse and changes its generated context surface.
    ///
    /// Validation rejects lexer diagnostics, parser recovery, recovered error
    /// nodes, and missing generated required children before constructing the
    /// validated-tree type boundary.
    pub fn validate(self) -> Result<CodegenApiValidatedTree, CodegenApiValidationError> {
        let lexer = self.parser.token_stream().number_of_source_errors();
        let parser = self.parser.number_of_syntax_errors();
        if lexer != 0 || parser != 0 {
            return Err(CodegenApiValidationError::SyntaxErrors { lexer, parser });
        }
        let parsed = self.parser.into_parsed_file(self.result);
        validate_tree_structure(&parsed)?;
        Ok(CodegenApiValidatedTree::__new(parsed))
    }
}

/// Parses UTF-8 text by constructing the lexer, token stream, parser, and
/// caller-selected entry rule in one call.
///
/// Pass the generated lexer constructor and a parser entry rule, for example
/// `parse(src, MyGrammarLexer::new, CodegenApiParser::file)`.
///
/// The returned [`antlr4_runtime::ParsedFile`] owns the canonical token store,
/// flat CST storage, and entry-rule root.
/// Use [`parse_with_parser`] instead when the caller also needs parser
/// diagnostics after the entry rule runs.
pub fn parse<L: TokenSource>(
    input: impl AsRef<str>,
    lexer: impl FnOnce(antlr4_runtime::InputStream) -> L,
    entry: impl FnOnce(&mut CodegenApiParser<L>) -> Result<antlr4_runtime::NodeId, antlr4_runtime::AntlrError>,
) -> Result<antlr4_runtime::ParsedFile, antlr4_runtime::AntlrError>
{
    parse_stream(antlr4_runtime::InputStream::new(input.as_ref()), lexer, entry)
}

/// Parses UTF-8 text and returns a typed tree whose required generated child
/// accessors are infallible.
pub fn parse_validated<L: TokenSource>(
    input: impl AsRef<str>,
    lexer: impl FnOnce(antlr4_runtime::InputStream) -> L,
    entry: impl FnOnce(&mut CodegenApiParser<L>) -> Result<antlr4_runtime::NodeId, antlr4_runtime::AntlrError>,
) -> Result<CodegenApiValidatedTree, CodegenApiValidationError>
{
    parse_stream_validated(
        antlr4_runtime::InputStream::new(input.as_ref()),
        lexer,
        entry,
    )
}

/// Parses UTF-8 text like [`parse`] while returning the parser after the entry
/// rule has run.
///
/// This keeps the compact generated setup path available for callers that also
/// need `Parser::number_of_syntax_errors()` or `CodegenApiParser::into_token_stream()`.
pub fn parse_with_parser<L: TokenSource, R>(
    input: impl AsRef<str>,
    lexer: impl FnOnce(antlr4_runtime::InputStream) -> L,
    entry: impl FnOnce(&mut CodegenApiParser<L>) -> Result<R, antlr4_runtime::AntlrError>,
) -> Result<CodegenApiParserParseOutput<R, L>, antlr4_runtime::AntlrError>
{
    parse_stream_with_parser(
        antlr4_runtime::InputStream::new(input.as_ref()),
        lexer,
        entry,
    )
}

/// Parses a caller-provided character stream by constructing the lexer, token
/// stream, parser, and caller-selected entry rule in one call.
///
/// Unlike [`parse`], this accepts any [`antlr4_runtime::CharStream`], including
/// a named [`antlr4_runtime::InputStream`] or a byte-oriented
/// [`antlr4_runtime::ByteStream`].
pub fn parse_stream<I: antlr4_runtime::CharStream, L: TokenSource>(
    input: I,
    lexer: impl FnOnce(I) -> L,
    entry: impl FnOnce(&mut CodegenApiParser<L>) -> Result<antlr4_runtime::NodeId, antlr4_runtime::AntlrError>,
) -> Result<antlr4_runtime::ParsedFile, antlr4_runtime::AntlrError>
{
    let CodegenApiParserParseOutput { result, parser } =
        parse_stream_with_parser(input, lexer, entry)?;
    Ok(parser.into_parsed_file(result))
}

/// Parses a caller-provided character stream and validates the completed tree.
pub fn parse_stream_validated<I: antlr4_runtime::CharStream, L: TokenSource>(
    input: I,
    lexer: impl FnOnce(I) -> L,
    entry: impl FnOnce(&mut CodegenApiParser<L>) -> Result<antlr4_runtime::NodeId, antlr4_runtime::AntlrError>,
) -> Result<CodegenApiValidatedTree, CodegenApiValidationError>
{
    let output = parse_stream_with_parser(input, lexer, entry)
        .map_err(CodegenApiValidationError::Recognition)?;
    output.validate()
}

/// Parses a caller-provided character stream like [`parse_stream`] while
/// returning the parser after the entry rule has run.
pub fn parse_stream_with_parser<I: antlr4_runtime::CharStream, L: TokenSource, R>(
    input: I,
    lexer: impl FnOnce(I) -> L,
    entry: impl FnOnce(&mut CodegenApiParser<L>) -> Result<R, antlr4_runtime::AntlrError>,
) -> Result<CodegenApiParserParseOutput<R, L>, antlr4_runtime::AntlrError>
{
    let lexer = lexer(input);
    let tokens = CommonTokenStream::new(lexer);
    let mut parser = CodegenApiParser::new(tokens);
    let result = entry(&mut parser)?;
    Ok(CodegenApiParserParseOutput { result, parser })
}

/// Generated parser. Each grammar rule is exposed as a public method.
///
/// Pick an entry-rule method that matches the grammar's intended
/// top-level construct for the input being parsed. The generator can
/// infer entry candidates from call paths that reach explicit `EOF`
/// matches, from parser rules that no other rule calls, and from
/// configured entry rules. It cannot infer the semantic choice
/// between multiple candidates.
///
/// Likely parser entry-rule methods:
/// - `root()`
///
/// All parser rule methods:
/// - `root()`
#[derive(Debug)]
pub struct CodegenApiParser<L, H = antlr4_runtime::NoSemanticHooks>
where
    L: TokenSource,
    H: antlr4_runtime::SemanticHooks,
{
    base: BaseParser<L, H>,
    simulator: Option<antlr4_runtime::ParserAtnSimulator<'static>>,
    generated_only: bool,
}

#[allow(dead_code)]
#[derive(Debug)]
enum GeneratedRuleError {
    Fatal(antlr4_runtime::AntlrError),
    Interpreted(antlr4_runtime::AntlrError),
}

impl GeneratedRuleError {
    fn into_error(self) -> antlr4_runtime::AntlrError {
        match self {
            Self::Fatal(error) | Self::Interpreted(error) => error,
        }
    }
}
impl<L> CodegenApiParser<L, antlr4_runtime::NoSemanticHooks>
where
    L: TokenSource,
{
    pub fn new(input: CommonTokenStream<L>) -> Self {
        Self::with_hooks(input, antlr4_runtime::NoSemanticHooks)
    }
}

impl<L, H> CodegenApiParser<L, H>
where
    L: TokenSource,
    H: antlr4_runtime::SemanticHooks,
{
    pub fn with_hooks(input: CommonTokenStream<L>, hooks: H) -> Self {
        let grammar_metadata = metadata();
        let data = grammar_metadata.recognizer_data();
        let base = BaseParser::with_semantic_hooks(input, data, hooks);
        Self {
            base,
            simulator: None,
            generated_only: std::env::var_os("ANTLR4_RUST_GENERATED_ONLY").is_some(),
        }
    }

    #[allow(dead_code)]
    fn parse_rule(&mut self, rule_index: usize) -> Result<antlr4_runtime::ParseTree, antlr4_runtime::AntlrError> {
        self.parse_rule_precedence(rule_index, 0)
    }

    #[allow(dead_code)]
    fn parse_rule_precedence(&mut self, rule_index: usize, precedence: i32) -> Result<antlr4_runtime::ParseTree, antlr4_runtime::AntlrError> {
        self.parse_rule_precedence_inner(rule_index, precedence, true)
    }

    #[allow(dead_code)]
    fn parse_rule_precedence_from_generated(&mut self, rule_index: usize, precedence: i32) -> Result<antlr4_runtime::ParseTree, antlr4_runtime::AntlrError> {
        self.parse_rule_precedence_inner(rule_index, precedence, false)
    }

    #[allow(dead_code)]
    fn parse_rule_precedence_inner(&mut self, rule_index: usize, precedence: i32, allow_generated_fallback: bool) -> Result<antlr4_runtime::ParseTree, antlr4_runtime::AntlrError> {
        if allow_generated_fallback {
            // True top-level entry: drop any fail-loud coordinates left by a
            // previous parse so a reused parser starts clean. Mid-parse the hits
            // are preserved so a generated parent can surface a recovered child's
            // fail-loud coordinate at this boundary.
            self.base.reset_unknown_semantic_hits();
            // Likewise drop stale sticky aborts (depth-cap violation,
            // parse-listener abort): entry rules share one parser instance,
            // and the flags must not poison the next parse when the previous
            // one exited through an error path.
            let _ = self.base.take_parse_abort();
        }
        let __rule_start = antlr4_runtime::IntStream::index(self.base.input());
        let __generated_only = self.generated_only();
        let __tree = if let Some(result) = self.parse_generated_rule(rule_index, precedence, allow_generated_fallback) {
            match result {
                Ok(tree) => tree,
                Err(error) => {
                    antlr4_runtime::IntStream::seek(self.base.input(), __rule_start);
                    let __report_error =
                        matches!(&error, GeneratedRuleError::Fatal(_));
                    // A fatal unwind retains recovery diagnostics committed
                    // earlier in this entry. Dispatch them before a semantic
                    // or parser-abort override can return, or they would leak
                    // into the next entry on a reused parser.
                    if allow_generated_fallback && __report_error {
                        self.base.report_generated_parser_diagnostics();
                    }
                    if allow_generated_fallback {
                        // A sticky abort (depth cap, listener) wins over an
                        // error or semantic miss derived after recovery absorbed
                        // the aborted rule. Drain any masked semantic miss too,
                        // so neither condition poisons the next entry.
                        if let Some(abort) = self.base.take_parse_abort() {
                            let _ = self.base.take_unknown_semantic_error();
                            return Err(abort);
                        }
                        // A generated predicate that consulted an unimplemented
                        // hook fails the alternative and surfaces here as a generic
                        // failed-predicate/rule error. Prefer the recorded fail-loud
                        // semantic error when no parser abort occurred.
                        if let Some(semantic_error) = self.base.take_unknown_semantic_error() {
                            return Err(semantic_error);
                        }
                    }
                    let error = error.into_error();
                    if allow_generated_fallback && __report_error {
                        self.base.report_unrecovered_parser_error(&error);
                    }
                    return Err(error);
                }
            }
        } else if __generated_only {
            return Err(antlr4_runtime::AntlrError::Unsupported(format!("generated parser did not emit rule {}", rule_index)));
        } else {
            self.parse_interpreted_rule_precedence(rule_index, precedence)?
        };
        if allow_generated_fallback {
            self.base.report_generated_parser_diagnostics();
            // A sticky abort (depth-cap violation, listener abort) is not a
            // syntax error: rule-level recovery may have produced a tree
            // and semantic miss anyway, but the abort is the root cause. Drain
            // both sticky conditions before returning so parser reuse is clean.
            if let Some(error) = self.base.take_parse_abort() {
                let _ = self.base.take_unknown_semantic_error();
                return Err(error);
            }
            // Surface unknown predicate/action coordinates recorded under the
            // Error policy only after parser aborts have been ruled out.
            if let Some(error) = self.base.take_unknown_semantic_error() {
                return Err(error);
            }
        }
        Ok(__tree)
    }

    #[allow(dead_code)]
    fn parse_interpreted_rule(&mut self, rule_index: usize) -> Result<antlr4_runtime::ParseTree, antlr4_runtime::AntlrError> {
        self.parse_interpreted_rule_precedence(rule_index, 0)
    }

    #[allow(dead_code)]
    fn parse_interpreted_rule_precedence(&mut self, rule_index: usize, precedence: i32) -> Result<antlr4_runtime::ParseTree, antlr4_runtime::AntlrError> {
        if precedence == 0 && true && std::env::var_os("ANTLR4_RUST_ADAPTIVE_DIRECT").is_some() {
            let simulator = self
                .simulator
                .get_or_insert_with(|| antlr4_runtime::ParserAtnSimulator::new_shared(atn()));
            self.base
                .parse_atn_rule_adaptive_or_fallback(atn(), simulator, rule_index)
        } else {
self.base.parse_atn_rule_with_precedence(atn(), rule_index, precedence)
        }
    }

    #[allow(dead_code)]
    fn parse_generated_rule(&mut self, rule_index: usize, precedence: i32, allow_fallback: bool) -> Option<Result<antlr4_runtime::ParseTree, GeneratedRuleError>> {
        let _ = precedence;
        let _ = allow_fallback;
        match rule_index {
            0 => Some(self.parse_generated_rule_0_dispatch(precedence, allow_fallback)),
            _ => None,
        }
    }

    #[allow(dead_code)]
    fn parse_generated_rule_0_dispatch(&mut self, precedence: i32, allow_fallback: bool) -> Result<antlr4_runtime::ParseTree, GeneratedRuleError> {
        let _ = precedence;
        antlr4_runtime::__antlr4_rust_generated_rule! { dispatch self, 0, GeneratedRuleError::Fatal; self.parse_generated_rule_0(precedence, allow_fallback) }
    }

    #[allow(dead_code)]
    fn parse_generated_rule_0(&mut self, __precedence: i32, allow_fallback: bool) -> Result<antlr4_runtime::ParseTree, GeneratedRuleError> {
        let _ = __precedence;
        antlr4_runtime::__antlr4_rust_generated_rule! {
            ordinary self, 0isize, 0, allow_fallback, atn(), GeneratedRuleError::Fatal;
            retry [none];
            bind (__ctx, __rule_start, __consumed_eof, __sync_error);
            setup {}
            body {
                self.base.match_token_into(1, 3, atn(), &mut __ctx, &mut __consumed_eof)?;
                self.base.match_token_into(-1, 4, atn(), &mut __ctx, &mut __consumed_eof)?;
            }
            success {}
            recovery {}
        }
    }



    pub fn root(&mut self) -> Result<antlr4_runtime::ParseTree, antlr4_runtime::AntlrError> {
        self.parse_rule(0)
    }


    fn run_action(&mut self, _action: antlr4_runtime::ParserAction, _tree: antlr4_runtime::ParseTree) {}

}



antlr4_runtime::__antlr4_rust_parser_facade! {
    type: CodegenApiParser<L, H>,
    fields: {
        base: base,
        simulator: simulator,
        generated_only: generated_only,
    },
    metadata: metadata,
    parser_atn: parser_atn,
    reset(parser) {
    }
}
}

#[allow(warnings, missing_docs, clippy::all, clippy::pedantic, clippy::nursery)]
pub use self::__antlr4_rust_generated::*;
